### PR TITLE
Use static parsing instead of requiring a binary.

### PR DESCRIPTION
**Pull request by bpflanz-adfin**
Using go/parser requires a built binary of the code to be enum'ed to
exist. This leads to two problems:
  1. The binary may be very out of date with the code, for example, when
  pulling into an existing repo that was last built locally some time
  ago, running jsonenums on newly added files will fail;
  2. If the binary has never been built, but the code already expects
  the output of jsonenums, it will be impossible to generate the enums,
  making it impossible to build the binary.

In response to a similar issue, Alan Donovan of the Go team suggested
that instead generating tools should be using (the not-yet stable)
x/tools/go/loader package to parse the actual Go code itself rather than
the compilation output: golang/go#11415

This change uses the suggested approach to break the bootstrapping
dependency cycle.

---
This change is [Reviewable](https://reviewable.io/reviews/adfin/jsonenums/1)

### CODE REVIEW

**Comment by BKadishAdFin** [comment]
Reviewed 2 of 3 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[parser/parser.go, line 31 \[r2\]](https://reviewable.io:443/reviews/adfin/jsonenums/1#-KFt9_ctQyfP2Z0fXddG:-KFt9_ctQyfP2Z0fXddH:-445134730) ([raw file](https://github.com/adfin/jsonenums/blob/66170bf81fa349ebc7710260c21250d1ef0bbdf7/parser/parser.go#L31)):*
Why the heck do you pass two unused variables?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/adfin/jsonenums/1)*

**Comment by bpflanz-adfin** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[parser/parser.go, line 31 \[r2\]](https://reviewable.io:443/reviews/adfin/jsonenums/1#-KFt9_ctQyfP2Z0fXddG:-KFtQ5bM2ea1gV4z2ZvW:-499146009) ([raw file](https://github.com/adfin/jsonenums/blob/66170bf81fa349ebc7710260c21250d1ef0bbdf7/parser/parser.go#L31)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/adfin/jsonenums/1)*

**Comment by BKadishAdFin** [comment]
Reviewed 1 of 3 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/adfin/jsonenums/1)*

**Comment by BKadishAdFin** [comment]
:lgtm:

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/adfin/jsonenums/1#-:-KFtQS15NjnKnJ1tfHJv:1417088721)*

**Pull request merged**
